<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.tahopen</groupId>
    <artifactId>tahopen-osgi-bundles</artifactId>
    <version>0.1.0.0</version>
  </parent>

  <groupId>org.tahopen</groupId>
  <artifactId>osgi-blueprint-api-module</artifactId>
  <packaging>bundle</packaging>
  
  <name>Tahopen Community Edition Project: ${project.artifactId}</name>
  <description>Tahopen OSGI Bundles</description>
  <url>https://www.tahopen.org</url>
  
  <scm>
    <connection>scm:git:git://github.com/tahopen/tahopen-osgi-bundles.git</connection>
    <developerConnection>scm:git:git@github.com:tahopen/tahopen-osgi-bundles.git</developerConnection>
    <url>https://github.com/tahopen/tahopen-osgi-bundles</url>
  </scm>  
  
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
      <comments>A business-friendly OSS license</comments>
    </license>
  </licenses>
  
  <developers>
    <developer>
      <name>Bryan Rosander</name>
      <email>brosander@pentaho.com</email>
      <roles>
        <role>developer</role>
      </roles>
    </developer>
    
    <developer>
      <name>Nick Baker</name>
      <email>nbaker@pentaho.com</email>
      <roles>
        <role>developer</role>
      </roles>
    </developer>
  </developers>

  <dependencies>
    <dependency>
      <groupId>org.apache.aries.blueprint</groupId>
      <artifactId>org.apache.aries.blueprint.api</artifactId>
      <version>1.0.1</version> 
      <scope>provided</scope>
    </dependency>
    <!-- Test -->
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-all</artifactId>
      <version>${mockito.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

</project>
